### ISSUE TITLE
Enhancement Request - NL language

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/TimVer#17]
### Brief summary of your request

Add NL Language

### Request details

@CMTriX

Could you please translate it in Dutch?

- Info
https://github.com/Timthreetwelve/TimVer/blob/main/TimVer/Languages/Strings.en-US.xaml

- Download
https://raw.githubusercontent.com/Timthreetwelve/TimVer/main/TimVer/Languages/Strings.en-US.xaml

**Comment by CMTriX** [comment]
[Strings.nl-NL.zip](https://github.com/Timthreetwelve/TimVer/files/13299329/Strings.nl-NL.zip)

**Comment by bovirus** [comment]
@CMTriX

Thanks.
Added Dutch .xaml language
Added Dutch strings into installer scripts.
