### ISSUE TITLE
Translation Update Request

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/TimVer#24]
### Report a problem with a translation

@CMTriX @vaso73

I hope that 2024 has been kind to you so far. 

I was hoping that you could find time to update the language files you previously contributed found [here](https://github.com/Timthreetwelve/TimVer/tree/main/TimVer/Languages) for the TimVer application.

I'm also hoping that you can find some time to translate the following. These phrases are for the installers I'm using. Once translated, I will copy them to GetMyIP, WUView, TimVer and whatever I'm forgetting as I type this. 

```xml
en.NotSelfContained=This will install the standard version of %1 version %2.%n%nThis version requires an existing installation of .NET 8 Desktop Runtime and is compatible with both x64 and x86 systems.%n%nIt Is recommended that you close all other applications before continuing.%n%nClick 'Next' to continue, or 'Cancel' to exit Setup.

en.SelfContainedx86=This will install the self-contained x86 (32-bit) version of %1 version %2.%n%nIt Is recommended that you close all other applications before continuing.%n%nClick 'Next' to continue, or 'Cancel' to exit Setup.

en.SelfContainedx64=This will install the self-contained x64 (64-bit) version of %1 version %2.%n%nIt Is recommended that you close all other applications before continuing.%n%nClick 'Next' to continue, or 'Cancel' to exit Setup.
```

Where %1 = application name, %2 = version number, %n = new line.

Thank you so much,
Tim

**Comment by CMTriX** [comment]
**Dutch**
en.SelfContainedx64= Hiermee wordt de portable x64 (64-bits) versie van %1 versie %2 geïnstalleerd.%n%n%nHet wordt aanbevolen om alle andere toepassingen te sluiten voordat u doorgaat.%n%nKlik op 'volgende' om door te gaan of op 'annuleren' om de installatie af te sluiten.

en.NotSelfContained=Hiermee wordt de standaardversie van %1 versie %2 geïnstalleerd.%n%n%nDeze versie vereist een bestaande installatie van .NET 8 Desktop Runtime en is compatibel met zowel x64- als x86-systemen.%n%nHet wordt aanbevolen om alle andere toepassingen te sluiten voordat u doorgaat.%n%nKlik op 'volgende' om door te gaan of op 'annuleren' om de installatie af te sluiten.

en.SelfContainedx86=Hiermee wordt de portable x86 (32-bits) versie van %1 versie %2 geïnstalleerd.%n%n%nHet wordt aanbevolen om alle andere toepassingen te sluiten voordat u doorgaat.%n%nKlik op 'volgende' om door te gaan of op 'annuleren' om de installatie af te sluiten.

**Comment by Timthreetwelve** [comment]
Thank you!
