### ISSUE TITLE
Translation: How to test a new translation

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/TimVer#26]
### Report a problem with a translation

@Timthreetwelve 

Could you please explain how to test a new translation before to update it on Github? 

- Where can I copy (path) the .xaml file?
- How can set the program to use external .xaml langauge file?
 

### If this is a contribution, enter the language name and code

Italian (it-IT)

### If this is a contribution, enter the language name as it is spelled locally

Italiano

**Comment by Timthreetwelve** [comment]
@bovirus 

I need to apologize for letting this issue sit so long before answering.

To test a language file in TimVer, 

- Navigate to the Settings page and scroll down to Language and open that section.
- Check the Enable language testing checkbox. If the checkbox wasn't previously checked, the app will restart.

![TimVer_2024-05-13_17-11-44](https://github.com/Timthreetwelve/TimVer/assets/43152358/9a100b1e-c70c-46f8-8481-4f4af25a773a)

- Next, click the Open App Folder button. File Explorer should open and `Strings.test.xaml` should be highlighted. 

![explorer_2024-05-13_17-14-35](https://github.com/Timthreetwelve/TimVer/assets/43152358/41a19600-3728-4a55-81cd-32262ee104ee)

- Open `Strings.test.xaml` with your editor of choice. Add or update strings and save the file. Alternatively, you could make a backup copy of `Strings.test.xaml`, then copy `Strings.it-IT.xaml`, or any other language file, into that folder and rename it to `Strings.test.xaml`.
- When you are ready, restart the app and you should see your changes.
- When you are done testing, simply uncheck the Enable language testing checkbox.

This same procedure for any of my apps that support multiple languages.

---

If you want to validate a language file, use the [Check Language File utility](https://github.com/Timthreetwelve/CheckLanguageFile?tab=readme-ov-file#check-language-file). It can also be used to compare two language files and find missing strings.

![CheckLanguageFile_2024-05-13_17-36-59](https://github.com/Timthreetwelve/TimVer/assets/43152358/b49c9dc0-4eae-4aef-b958-ebedc312e9ac)

**Comment by bovirus** [comment]
Thanks.
