### ISSUE TITLE
French translation for TimVer_0.9.0.0

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/TimVer#39]
### Discussed in https://github.com/Timthreetwelve/TimVer/discussions/38

<div type='discussions-op-text'>

<sup>Originally posted by **logounet** June 10, 2024</sup>
Hello,

I have updated your French translation for TimVer_0.9.0.0 (corrected errors and titled...) if you accept it. Attached is the file Strings.fr-FR.xaml.zip

[Strings.fr-FR.xaml.zip](https://github.com/user-attachments/files/15760333/Strings.fr-FR.xaml.zip)

Best regards</div>

**Comment by Timthreetwelve** [comment]
@logounet Thank you so much for updating the French language file. It will be in the next release.

I'm creating an issue from this discussion so that I can track it.

Thanks again,
Tim

**Comment by Timthreetwelve** [comment]
@logounet Your updated translations have been included in version 0.9.1 which was released today. Thanks again!

Tim

**Comment by logounet** [comment]
Hello,

I have updated the French translation for TimVer_0.9.4.0 if you accept it. Attached is the file
 Strings.fr-FR.xaml.zip


[Strings.fr-FR.xaml.zip](https://github.com/user-attachments/files/17145152/Strings.fr-FR.xaml.zip)


Best regards
