### ISSUE TITLE
Enahncement - Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/TimVer#5]
### Brief summary of your request

Enable multilanguage GUI

### Request details

Could you please to consider to modify source code to have multilanguage interface?

I can help with italian.

I propose to have separate file for each language.

**Comment by bovirus** [comment]
@Timthreetwelve 

Could you plaese make some changes as for other programs?

Multilanguage GUI
Multilanguage instaler
Use of exeternal .xaml language file for translation etsting?

Thanks.

**Comment by Timthreetwelve** [comment]
Yes, to all three. I've already begun work on it.  My plan is to get the latest updates to WUView and GetMyIP released and then resume working on TimVer. Then I really need to work on [My Scheduled Tasks](https://github.com/Timthreetwelve/MyScheduledTasks).

Before I call it quits for the day I'll see if I can push any of the TimVer stuff up to GitHub. 

Also, if you haven't seen it, look at https://github.com/Timthreetwelve/GetMyIP/issues/43

**Comment by Timthreetwelve** [comment]
@bovirus 

I moved the Inno Setup script into the solution. It's going to need your magic touch. 😃

I also pushed the latest update to Strings.en-US.xaml. It isn't complete yet, but if you want to start on a translation go ahead.

Tim

**Comment by Timthreetwelve** [comment]
@bovirus 

It took a while, but I finally got there. Version 0.8.5 has been released.

Thanks again for all your help!

Tim

**Comment by bovirus** [comment]
@Timthreetwelve 

Thank you for your new program release.

Happy new year.
