### ISSUE TITLE
Problem with Strings.it-IT.xaml

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/TimVer#56]
### Report a problem with a translation

@bovirus 

There's a minor problem with the latest Strings.it-IT.xaml. The `GraphicsInfo_SelectAdapterToolTipLine2` key is duplicated on lines 139 - 140 and `GraphicsInfo_SelectAdapter` has been deleted.

I'm sorry that I didn't catch this until today.

I've also added one new string today.

Tim

**Comment by bovirus** [comment]
@Timthreetwelve 

Sorry for the error.

I updated the file in PR.

Thanks.

**Comment by Timthreetwelve** [comment]
Thank you!
