### ISSUE TITLE
Enhancement Request: GUI - Increase size of translation language list

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/TimVer#65]
### Brief summary of your request

The box for translation language leist could be bigger

### Request details

@Timthreetwelve 

Please check screenshot
If you can increase box width/height

![image](https://github.com/user-attachments/assets/d53a8961-346a-4cf6-b55b-cc22d121aed0)

Thanks.

**Comment by Timthreetwelve** [comment]
@bovirus 

I've never been completely happy with it either, do you like the way I changed it in GetMyIP? 
![GetMyIP_2024-09-26_15-48-29](https://github.com/user-attachments/assets/e543c798-2f34-402b-8a5a-0e56434f181c)

**Comment by bovirus** [comment]
@Timthreetwelve 

Any solution that you like is ok.
My idea is to use as much as possible the GUI space to avoid when you can scroll to show all info.
