### ISSUE TITLE
Dutch update?

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/TimVer#75]
### Report a problem with a translation

@CMTriX 

I'm getting TimVer ready for a new release and I have copied the Dutch strings related to Settings export/import from Get My IP.

Would you mind double checking [String.nl-NL.xaml](https://github.com/Timthreetwelve/TimVer/tree/main/TimVer/Languages) and also contribute the missing strings? I've pasted the missing strings below.

Also, I've just noticed the spelling of "OVer" on the About page. I have a feeling that it might be a joke on the spelling of TimVer.

![2024-12-08_15-31-13](https://github.com/user-attachments/assets/e0d098a5-49f1-4257-89c6-7a56c0120d19)

Thanks a ton!
Tim

### Contribute a translation

```shell
[TimVer] Languages/Strings.nl-NL.xaml is missing the following keys:
Key: DriveInfo_BootDrive                    en-US Value: "Boot Drive"
Key: DriveInfo_DeviceID                     en-US Value: "Device ID"
Key: DriveInfo_DriveLetters                 en-US Value: "Drive Letters"
Key: DriveInfo_FriendlyName                 en-US Value: "Friendly Name"
Key: DriveInfo_PartitionStyle               en-US Value: "Partition Style"
Key: DriveInfo_SerialNumber                 en-US Value: "Serial Number"
Key: DriveInfo_SystemDrive                  en-US Value: "System Drive"
Key: GraphicsInfo_NumberOfDisplays          en-US Value: "Number of Displays"
Key: HardwareInfo_BIOS                      en-US Value: "BIOS"
Key: HardwareInfo_BiosMode                  en-US Value: "BIOS Mode"
Key: HardwareInfo_LastBootNormal            en-US Value: "Normal Boot"
Key: HardwareInfo_LastBootSafe              en-US Value: "Safe Mode"
Key: HardwareInfo_LastBootSafeNetwork       en-US Value: "Safe Mode with Networking"
Key: HardwareInfo_LastBootType              en-US Value: "Last Reboot Type"
Key: HardwareInfo_ProcessorDescription      en-US Value: "Processor Description"
Key: HardwareInfo_SecureBoot                en-US Value: "Secure Boot"
Key: HardwareInfo_SecureBoot_Disabled       en-US Value: "Disabled"
Key: HardwareInfo_SecureBoot_Enabled        en-US Value: "Enabled"
Key: HardwareInfo_UEFI                      en-US Value: "UEFI"
Key: HardwareInfo_Uptime                    en-US Value: "Uptime"
Key: HardwareInfo_UptimeString              en-US Value: "{0} days, {1} hours, {2} minutes, {3} seconds"
Key: MsgText_CopiedToClipboardItem          en-US Value: "Item was copied to the clipboard"
Key: MsgText_ErrorGeneral                   en-US Value: "An error has occurred."
Key: MsgText_OptionReset                    en-US Value: "Option has been reset"
Key: SettingsItem_ShowBootDriveColumn       en-US Value: "Show Boot Drive column"
Key: SettingsItem_ShowDriveLettersColumn    en-US Value: "Show Drive Letters column"
Key: SettingsItem_ShowFriendlyName          en-US Value: "Show Friendly Name column"
Key: SettingsItem_ShowPartitionStyleColumn  en-US Value: "Show Partition Style column"
Key: SettingsItem_ShowSerialNumber          en-US Value: "Show Serial Number column"
Key: SettingsItem_ShowVideoSelector         en-US Value: "Show video adapter selector on Graphics (Video) page"
Key: WindowsInfo_DotNetVersion              en-US Value: ".NET Version"
```

**Comment by CMTriX** [comment]
where is my translation with updates ..?

is it deleted?

**Comment by Timthreetwelve** [comment]
I've pushed it again. I'm thinking that this might be related to the problem that caused #74. 

https://github.com/Timthreetwelve/TimVer/blob/main/TimVer/Languages/Strings.nl-NL.xaml

I need to check the other language file as well.

Tim

**Comment by CMTriX** [comment]
i had these :

[TimVer] Languages/Strings.nl-NL.xaml is missing the following keys:
Key: DriveInfo_BootDrive                    en-US Value: "Boot Drive"
Key: DriveInfo_DeviceID                     en-US Value: "Device ID"
Key: DriveInfo_DriveLetters                 en-US Value: "Drive Letters"
Key: DriveInfo_FriendlyName                 en-US Value: "Friendly Name"
Key: DriveInfo_PartitionStyle               en-US Value: "Partition Style"
Key: DriveInfo_SerialNumber                 en-US Value: "Serial Number"
Key: DriveInfo_SystemDrive                  en-US Value: "System Drive"
Key: GraphicsInfo_NumberOfDisplays          en-US Value: "Number of Displays"
Key: HardwareInfo_BIOS                      en-US Value: "BIOS"
Key: HardwareInfo_BiosMode                  en-US Value: "BIOS Mode"
Key: HardwareInfo_LastBootNormal            en-US Value: "Normal Boot"
Key: HardwareInfo_LastBootSafe              en-US Value: "Safe Mode"
Key: HardwareInfo_LastBootSafeNetwork       en-US Value: "Safe Mode with Networking"
Key: HardwareInfo_LastBootType              en-US Value: "Last Reboot Type"
Key: HardwareInfo_ProcessorDescription      en-US Value: "Processor Description"
Key: HardwareInfo_SecureBoot                en-US Value: "Secure Boot"
Key: HardwareInfo_SecureBoot_Disabled       en-US Value: "Disabled"
Key: HardwareInfo_SecureBoot_Enabled        en-US Value: "Enabled"
Key: HardwareInfo_UEFI                      en-US Value: "UEFI"
Key: HardwareInfo_Uptime                    en-US Value: "Uptime"
Key: HardwareInfo_UptimeString              en-US Value: "{0} days, {1} hours, {2} minutes, {3} seconds"
Key: MsgText_CopiedToClipboardItem          en-US Value: "Item was copied to the clipboard"
Key: MsgText_ErrorGeneral                   en-US Value: "An error has occurred."
Key: MsgText_OptionReset                    en-US Value: "Option has been reset"
Key: SettingsItem_ShowBootDriveColumn       en-US Value: "Show Boot Drive column"
Key: SettingsItem_ShowDriveLettersColumn    en-US Value: "Show Drive Letters column"
Key: SettingsItem_ShowFriendlyName          en-US Value: "Show Friendly Name column"
Key: SettingsItem_ShowPartitionStyleColumn  en-US Value: "Show Partition Style column"
Key: SettingsItem_ShowSerialNumber          en-US Value: "Show Serial Number column"
Key: SettingsItem_ShowVideoSelector         en-US Value: "Show video adapter selector on Graphics (Video) page"
Key: WindowsInfo_DotNetVersion              en-US Value: ".NET Version"

changed, but it is gone.

i also did changes 44 minutes ago, it is now undone, all typo's are back !

**Comment by CMTriX** [comment]
i did this also:

https://github.com/Timthreetwelve/TimVer/compare/main...CMTriX:TimVer:patch-4?expand=1

**Comment by CMTriX** [comment]
ah, i see it is here with the previous changes:

https://github.com/Timthreetwelve/TimVer/compare/main...CMTriX:TimVer:patch-3?expand=1

**Comment by CMTriX** [comment]
<sys:String x:Key="DriveInfo_BootDrive">Opstartschijf</sys:String>
<sys:String x:Key="DriveInfo_DeviceID">Apparaat ID</sys:String>
<sys:String x:Key="DriveInfo_DriveLetters">Stationletters</sys:String>
<sys:String x:Key="DriveInfo_FriendlyName">Stationsnaam</sys:String>
<sys:String x:Key="DriveInfo_PartitionStyle">Partitie opmaak</sys:String>
<sys:String x:Key="DriveInfo_SerialNumber">Serienummer</sys:String>
<sys:String x:Key="DriveInfo_SystemDrive">Systeemschijf</sys:String>
<sys:String x:Key="GraphicsInfo_NumberOfDisplays">Aantal monitoren</sys:String>
<sys:String x:Key="HardwareInfo_BIOS">BIOS</sys:String>
<sys:String x:Key="HardwareInfo_BiosMode">Biosmode</sys:String>
<sys:String x:Key="HardwareInfo_LastBootNormal">Normale opstart</sys:String>
<sys:String x:Key="HardwareInfo_LastBootSafe">Veilige modus</sys:String>
<sys:String x:Key="HardwareInfo_LastBootSafeNetwork">Veilige modus met netwerk</sys:String>
<sys:String x:Key="HardwareInfo_LastBootType">Laatste reboot type</sys:String>
<sys:String x:Key="HardwareInfo_ProcessorDescription">Processor omschrijving</sys:String>
<sys:String x:Key="HardwareInfo_SecureBoot">Veilieg opstart</sys:String>
<sys:String x:Key="HardwareInfo_SecureBoot_Disabled">Uitgeschakeld</sys:String>
<sys:String x:Key="HardwareInfo_SecureBoot_Enabled">Ingeschakeld</sys:String>
<sys:String x:Key="HardwareInfo_UEFI">UEFI</sys:String>
<sys:String x:Key="HardwareInfo_Uptime">Uptime</sys:String>
<sys:String x:Key="HardwareInfo_UptimeString">{0} dag, {1} uren, {2} minuten, {3} seconden</sys:String>
<sys:String x:Key="MsgText_CopiedToClipboardItem">Item gekopieerd naar klembord</sys:String>
<sys:String x:Key="MsgText_ErrorGeneral">Er is een fout opgetreden</sys:String>
<sys:String x:Key="MsgText_OptionReset">Optie is hersteld</sys:String>
<sys:String x:Key="SettingsItem_ShowBootDriveColumn">Toon opstartschijf kolom</sys:String>
<sys:String x:Key="SettingsItem_ShowDriveLettersColumn">Toon stationletters</sys:String>
<sys:String x:Key="SettingsItem_ShowFriendlyName">Toon stationsnaam kolom</sys:String>
<sys:String x:Key="SettingsItem_ShowPartitionStyleColumn">Toon partitie opmaak kolom</sys:String>
<sys:String x:Key="SettingsItem_ShowSerialNumber">Toon serinummer kolom</sys:String>
<sys:String x:Key="SettingsItem_ShowVideoSelector">Toon videoadapterselector op de grafische (video) pagina</sys:String>
<sys:String x:Key="WindowsInfo_DotNetVersion">.NET versie</sys:String>

**Comment by CMTriX** [comment]
There is error on top:

 Can’t automatically merge. Don’t worry, you can still create the pull request.

**Comment by Timthreetwelve** [comment]
I'm sorry that this is so messed up.

I have an appointment this afternoon. I'll pick this back up later today.

Thanks for your help and patience.

Tim

**Comment by Timthreetwelve** [comment]
Version 0.10.0 released moments ago.
